version: '3.8'

networks:
  laravel:
    name: laravel

services:
    
  nginx:
    # image: nginx:stable-alpine
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    depends_on:
      - php
      - mysql
    ports:
      - 80:80
      - 443:443
    volumes:
      # - ./src:/usr/share/nginx/html
      - ./src:/var/www/html
    networks:
      - laravel
    
  # apache:
  #   # image: nginx:stable-alpine
  #   build:
  #     context: .
  #     dockerfile: apache.dockerfile
  #   container_name: apache
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     # - ./src:/usr/share/nginx/html
  #     - ./src:/var/www/html
  #   networks:
  #     - laravel

  php:
    # image: php:8.3-fpm-alpine
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    user: "0:0"
    # command: bash -c "chmod o+w /var/www/html/storage/ -R"
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir:  /var/www/html
    networks:
      - laravel

  artisan:
    # image: php:8.3-fpm-alpine
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    user: "0:0"
    # command: bash -c "chmod o+w /var/www/html/storage/ -R"
    volumes:
      - ./src:/var/www/html
    working_dir:  /var/www/html
    entrypoint: ["php","artisan"]
    networks:
      - laravel

  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - 4306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel
    environment:
      - MYSQL_DATABASE=laraveldb
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret

  npm:
    image: node:current-alpine
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir:  /var/www/html
    entrypoint: ["npm"]
    networks:
      - laravel