version: '3.8'

networks:
  laravel:
    name: laravel

services:
    
  # nginx:
  #   # image: nginx:stable-alpine
  #   build:
  #     context: .
  #     dockerfile: nginx.dockerfile
  #   container_name: nginx
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     # - ./src:/usr/share/nginx/html
  #     - ./src:/var/www/html
  #   networks:
  #     - laravel
    
  apache:
    # image: nginx:stable-alpine
    build:
      context: .
      dockerfile: apache.dockerfile
    container_name: apache
    ports:
      - 80:80
      - 443:443
    volumes:
      # - ./src:/usr/share/nginx/html
      - ./src:/var/www/html
    networks:
      - laravel

  php:
    image: php:8.3-fpm-alpine
    container_name: php
    networks:
      - laravel

  mysql:
    image: mysql:8.3.0
    container_name: mysql
    networks:
      - laravel
    environment:
      - MYSQL_DATABASE=laraveldb
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
